export const goColors = {
  ink: "#231f20",
  inkSoft: "#3a3536",
  gold: "#e5b82e",
  goldHover: "#f0c84a",
  goldDark: "#c9971a",
  cream: "#fbf7ef",
  paper: "#ffffff",
  border: "#e7e2d8",
  muted: "#6f6a65",
  mutedLight: "#f4f1ea",
  success: "#147a4d",
  warning: "#a16207",
  danger: "#b42318",
  info: "#175cd3",
  gray: {
    50: "#faf9f7",
    100: "#f4f1ea",
    200: "#e7e2d8",
    300: "#d4cec3",
    400: "#a8a29a",
    500: "#6f6a65",
    600: "#524e4a",
    700: "#3a3536",
    800: "#2d292a",
    900: "#231f20",
    950: "#1a1718",
  },
} as const;

export const semanticColors = {
  light: {
    background: goColors.cream,
    foreground: goColors.ink,
    surface: goColors.paper,
    surfaceElevated: goColors.paper,
    surfaceMuted: goColors.mutedLight,
    primary: goColors.gold,
    primaryForeground: goColors.ink,
    secondary: goColors.mutedLight,
    secondaryForeground: goColors.ink,
    accent: goColors.gold,
    accentForeground: goColors.ink,
    border: goColors.border,
    ring: goColors.gold,
    muted: goColors.mutedLight,
    mutedForeground: goColors.muted,
    destructive: goColors.danger,
    destructiveForeground: goColors.paper,
    success: goColors.success,
    warning: goColors.warning,
  },
  dark: {
    background: goColors.gray[950],
    foreground: goColors.paper,
    surface: goColors.gray[900],
    surfaceElevated: goColors.gray[800],
    surfaceMuted: goColors.gray[800],
    primary: goColors.gold,
    primaryForeground: goColors.ink,
    secondary: goColors.gray[800],
    secondaryForeground: goColors.paper,
    accent: goColors.gold,
    accentForeground: goColors.ink,
    border: goColors.gray[700],
    ring: goColors.gold,
    muted: goColors.gray[800],
    mutedForeground: goColors.gray[400],
    destructive: goColors.danger,
    destructiveForeground: goColors.paper,
    success: goColors.success,
    warning: goColors.warning,
  },
} as const;
